services:
  postgres:
    container_name: postgres-debug
    volumes:
      - postgres_data_debug:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis-debug
    ports:
      - "6379:6379"

volumes:
  postgres_data_debug:
