[admin]
managers-mail-list = []

[files]
task-max-size-mb = 2
test-max-size-mb = 0.5
code-max-size-mb = 0.5

[runners]
timeout = 2
max-memory-mb=256

[runners.c]
gcc-parameters = '-Wall -g -ansi -pedantic -lm'
