#!/bin/bash

# find staged .py files
FILES=`git diff --name-only --cached --diff-filter=d`
PY_FILES=`venv/bin/python hooks/modified_py_files.py "$FILES"`
if [ -z "$PY_FILES" ]; then
    echo "No .py files changed - skipping tests, pylint, and mypy."
    exit 0;
fi

# run coverage report and create badge
echo "------------ 1. Run Tests ------------"
make code-coverage
if [ "$?" != "0" ]; then
    echo "Fix broken tests before commiting.";
    exit 1;
fi

# add badge to the current commit
git add metadata/coverage.svg

# run pylint on staged py files
"-------------- 2. Linter -------------"
make lint-hook files="$PY_FILES"
if [ "$?" != "0" ]; then
    echo "Fix lint issues before commiting.";
    echo "If you think it's safe to ignore them, run:";
    echo "git commit -n"
    exit 1;
fi

# run mypy
"---------- 3. Typing Checks ----------"
make type-check
if [ "$?" != "0" ]; then
    echo "Fix typing issues before commiting.";
    exit 1;
fi
