#!/bin/bash

cyan_echo() {
  CYAN='\033[0;36m'
  NC='\033[0m' # No Color
  echo -e "\n$CYAN$1$NC\n"
}

red_echo() {
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  echo -e "$RED$1$NC"
}

green_echo() {
  GREEN='\033[0;32m'
  NC='\033[0m' # No Color
  echo -e "\n$GREEN${1}$NC\n"
}

# find staged .py files
FILES=`git diff --name-only --cached --diff-filter=d`
PY_FILES=`venv/bin/python scripts/modified_py_files.py "$FILES"`
if [ -z "$PY_FILES" ]; then
    green_echo "No .py files changed - skipping tests, pylint, and mypy."
    exit 0;
fi

# run smoke test suite
cyan_echo "------------ 1. Run Tests ------------"
make smoke-test
if [ "$?" != "0" ]; then
    red_echo "\nFix broken tests before commiting.\n";
    exit 1;
fi

# run mypy
cyan_echo "---------- 2. Typing Checks ----------"
make type-check
if [ "$?" != "0" ]; then
    red_echo "\nFix typing issues before commiting.\n";
    exit 1;
fi

# run pylint on staged py files
cyan_echo "-------------- 3. Linter -------------"
make lint-hook files="$PY_FILES"
if [ "$?" != "0" ]; then
    red_echo "\nFix lint issues before commiting.";
    red_echo "If you think it's safe to ignore them, either disable the rule or run:";
    red_echo "git commit -n\n"
    exit 1;
fi

# success
make stop-test
echo -e "\n"
