name: Linter (Pylint)
run-name: Running Pylint
on:
  push:
    branches:
      - main
    paths:
      - code/**
      - configs/.pylintrc
  pull_request:
  workflow_dispatch:
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                persist-credentials: false
                fetch-depth: 0
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11
            - name: Install dependencies
              run: |
                 make setup
            - name: Run Pylint
              run: |
                  make lint
