name: Tests
run-name: Running tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'scripts/pre-commit'
      - 'metadata/**'
      - configs/mypy.ini
      - configs/deploy.ini
      - configs/.pylintrc
  workflow_dispatch:
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                persist-credentials: false
                fetch-depth: 0
            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - name: Generate .env.test
              run: |
                  echo MOSS_USER_ID=\"${{ secrets.MOSS_USER_ID }}\" > .env.test
                  echo PAPERTRAIL_ADDRESS=\"${{ secrets.PAPERTRAIL_ADDRESS }}\" >> .env.test
            - name: Install dependencies
              run: |
                  make setup
            - name: Run tests & gather coverage info
              uses: paambaati/codeclimate-action@v4.0.0
              with:
                coverageCommand: make test
                debug: true
            - name: Stop containers
              run: |
                  make stop-test
